import './style.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by GPT-4',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
